name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make docs
      run: |
        sudo apt-get update \
        sudo apt-get install -y apt \
        sudo apt−get install doxygen \
        make docs
      working-directory: L09
